AWSTemplateFormatVersion: 2010-09-09
Description: A private ECS service
Parameters:
  Environment:
    AllowedValues:
      - Dev
      - Staging
      - Production
    ConstraintDescription: Environment has to be one of Dev, Staging or Production
    Type: String
Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${AWS::StackName}-test
